[build]
  command = "npm run build" # or "yarn build" if using yarn
  publish = "dist" # Change this to "build" if using Create React App

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
